### ISSUE TITLE
Performance On MPII

### ISSUE THREAD

**Issue by Xiangyu-CAS** [wbenbihi/hourglasstensorlfow#11]
Hi， I am wondering if this tf implementation compete the orginial one? Did you ever test the performance on MPII dataset?
As my past experience , tensorflow implementations alwasy  show a slightly  reducement on performance . Could you share your test result on MPII ?
Thanks!

**Comment by wbenbihi** [comment]
Indeed, my model is less accurate than the MPII state of the art. I cannot state it's because of TensorFlow. The state of the art was implemented with 8 stacks I only use 4 to reduce computation time. My preprocessing and data augmentation may not be the same also. We would have to fix those differences before we can assert any efficiency downgrade due to TensorFlow. But I agree I have also heard that TensorFlow can be less accurate than other DL frameworks.

To answer your question with 4 stacks I have an overall PCKh of 91%. With huge difficulties on extremities such as wrists or ankles.

**Comment by dongzhuoyao** [comment]
Could you provide your code to generate MPII test set result?  @wbenbihi 😃
